"""Create many-to-many with user-clothes

Revision ID: 596b0e4c1a10
Revises: 83c105155c66
Create Date: 2022-06-21 20:21:16.929862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596b0e4c1a10'
down_revision = '83c105155c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_clothes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_clothes')
    # ### end Alembic commands ###
