"""secondary migration

Revision ID: 83c105155c66
Revises: 636286f91238
Create Date: 2022-06-21 18:34:12.005635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83c105155c66'
down_revision = '636286f91238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('user', 'create_on')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('create_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user', 'created_on')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
